from typing import List, Dict, Literal, Optional
from pydantic import BaseModel, Field

class Tool(BaseModel):
    name: str

class Agent(BaseModel):
    role: str = Field(..., description="The role of the agent")
    goal: str = Field(..., description="The goal of the agent")
    persona: str = Field(..., description="The persona of the agent")
    tools: List[str] = Field(..., description="tool names available to the agent; use only tools provided and do not make them up")
    dependencies: List[str] = Field(..., description="List of agent nodes this agent depends on")

class FunctionCall(BaseModel):
    arguments: dict
    """
    The arguments to call the function with, as generated by the model in JSON
    format. Note that the model does not always generate valid JSON, and may
    hallucinate parameters not defined by your function schema. Validate the
    arguments in your code before calling your function.
    """

    name: str
    """The name of the function to call."""

class FunctionDefinition(BaseModel):
    name: str
    description: Optional[str] = None
    parameters: Optional[Dict[str, object]] = None

class FunctionSignature(BaseModel):
    function: FunctionDefinition
    type: Literal["function"]