from typing import List, Dict, Literal, Optional
from pydantic import BaseModel, Field

class Tool(BaseModel):
    name: str

class Agent(BaseModel):
    role: str
    goal: str
    persona: str
    tools: List[str] = Field(..., alias="tools")
    verbose: bool
    dependencies: List[str] = Field(..., description= "directed edges to this agent")

class FunctionCall(BaseModel):
    arguments: dict
    """
    The arguments to call the function with, as generated by the model in JSON
    format. Note that the model does not always generate valid JSON, and may
    hallucinate parameters not defined by your function schema. Validate the
    arguments in your code before calling your function.
    """

    name: str
    """The name of the function to call."""

class FunctionDefinition(BaseModel):
    name: str
    description: Optional[str] = None
    parameters: Optional[Dict[str, object]] = None

class FunctionSignature(BaseModel):
    function: FunctionDefinition
    type: Literal["function"]